// swift-tools-version: 6.1
// Binary distribution Package.swift for AntifraudeSDK
// This version distributes a pre-compiled XCFramework instead of source code

import PackageDescription

let package = Package(
    name: "AntifraudeSDK",
    platforms: [
        .iOS(.v14)  // iOS 14+ for modern APIs including authorizationStatus
    ],
    products: [
        .library(
            name: "AntifraudeSDK",
            targets: ["AntifraudeSDK"]),
    ],
    dependencies: [
        // No external dependencies - we'll use URLSession for networking
        // and Core Location for geolocation (built into iOS)
    ],
    targets: [
        // Binary target - clients will download the pre-compiled framework
        .binaryTarget(
            name: "AntifraudeSDK",
            // Option 1: URL to a hosted .xcframework.zip file
            url: "https://github.com/Legitimuz-Tech/legitimuz-sdk-geoloc-ios/releases/download/1.0.0/AntifraudeSDK.xcframework.zip",
            checksum: "f55ec27f5057ea8b9687203c22216fb96d4460223da632472dac1b0b898b40b0"
            // Option 2: Local path (for testing)
            // path: "./AntifraudeSDK.xcframework.zip"
        ),
        .testTarget(
            name: "AntifraudeSDKTests",
            dependencies: ["AntifraudeSDK"]
        )
    ]
)

/*
Instructions for setting up binary distribution:

1. Build the XCFramework:
   - Install Xcode from App Store
   - Run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
   - Run: ./build_xcframework.sh

2. Host the binary:
   Option A - GitHub Releases (Recommended):
   - Create a new repository (e.g., AntifraudeSDK-Binary)
   - Upload the .xcframework.zip to GitHub Releases
   - Update the URL in the binaryTarget above
   
   Option B - Your own server:
   - Upload to your web server
   - Update the URL in the binaryTarget above

3. Update checksum:
   - Use the checksum generated by build_xcframework.sh
   - Replace "REPLACE_WITH_ACTUAL_CHECKSUM" with the actual value

4. Replace this file:
   - Rename Package.swift to Package-Source.swift (keep as backup)
   - Rename this file to Package.swift

5. Update your repository:
   - Remove the Sources/ directory from your main repository
   - Keep only Package.swift and README files
   - Clients will now download the binary instead of source code

Security Benefits:
- Source code is completely hidden from clients
- Binary is optimized and smaller
- Faster integration for clients (no compilation needed)
- Intellectual property protection
*/
